import React from "react";
// import Layout
import Layout from "@/components/Layout";
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import Image from "next/image";
//import RavinTeja.png
import EMS from  "./../../public/images/SS1.png";
import Inv from  "./../../public/images/SS2.png";
import Pro1 from "./../../public/images/SS3.png";
import Pro2 from "./../../public/images/SS4.png";
import Pro3 from "./../../public/images/SS5.png";
import Pro4 from "./../../public/images/SS6.png";
import {FeaturedProject,ProjectCard} from "@/components/ProjectCards";
import Link from "next/link";


const Projects = () => {
  return (
    <>
      <Head>
        <title>Ravin Teja | Projects Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark bg-light w-full min-h-screen">
        <Layout className="pt-16 p-8 lg:p-32 lg:pt-0">
          <AnimatedText
            text="Imagination Trumps Knowledge! "
            className="text-4xl sm:!text-6xl  sm:mb-8 xl:text-6xl lg:!text-8xl !leading-tight "
          />
          <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-24 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
            <div className="col-span-12 ">
              <FeaturedProject
                name="Employee Managemnt System"
                link="/"
                githubLink="/"
                imgURL={EMS} 
                description="Employee management system website that enables offline work to be easily uploaded and managed online, streamlining the process and increasing efficiency."
              />
            </div>
            <div className="col-span-12 md:col-span-6">
              <ProjectCard
                name="Assignement Submission"
                title="Employee Management System"
                link="/"
                githubLink="/"
                imgURL={Pro1}
              />
            </div>
            <div className="col-span-12 md:col-span-6">
              <ProjectCard
                name="Online Outing System"
                title="Employee Management System"
                link="/"
                githubLink="/"
                imgURL={Pro2}
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                name="Inverse Cooking"
                link="/"
                githubLink="/"
                imgURL={Inv}
                description="Inverse Cooking is a dataset of 1.2 million cooking recipes with 13.5 million cooking instructions automatically extracted from 800K food blogs. The dataset is unique in its size, diversity, and accuracy, and can be used for several downstream tasks such as cooking recipe retrieval, recipe classification, and ingredient prediction."
              />
            </div>
            <div className="col-span-12 md:col-span-6">
              <ProjectCard
                name="Optimal Crop Prediciton"
                title="Employee Management System"
                link="/"
                githubLink="/"
                imgURL={Pro3}
              />
            </div>
            <div className="col-span-12 md:col-span-6">
              <ProjectCard
                name="Online Shopping System"
                title="Employee Management System"
                link="/"
                githubLink="/"
                imgURL={Pro4}
              />
            </div>
          </div>
        </Layout>
      </main>{" "}
    </>
  );
};

export default Projects;
